apiVersion: v1
kind: Service
metadata:
  name: simple-java-app-service
  namespace: default
  labels:
    app: simple-java-app
spec:
  type: ClusterIP
  selector:
    app: simple-java-app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080